name: Auto-assign PR creator

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign-creator:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR creator
        uses: actions/github-script@v7
        with:
          script: |
            const prCreator = context.payload.pull_request.user.login;
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              assignees: [prCreator],
            });
