name: Auto-assign PR creator

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign-creator:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Assign PR creator
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} \
            --add-assignee "${{ github.event.pull_request.user.login }}"
